// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Pdist
arma::mat Pdist(arma::mat A, arma::mat B);
RcppExport SEXP _edfkmeans_Pdist(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(Pdist(A, B));
    return rcpp_result_gen;
END_RCPP
}
// edfkmeans
NumericVector edfkmeans(arma::mat X, arma::mat M, IntegerVector asg, IntegerVector ns, double SS, int nclust, int n, int d, NumericVector sig, int nsig);
RcppExport SEXP _edfkmeans_edfkmeans(SEXP XSEXP, SEXP MSEXP, SEXP asgSEXP, SEXP nsSEXP, SEXP SSSEXP, SEXP nclustSEXP, SEXP nSEXP, SEXP dSEXP, SEXP sigSEXP, SEXP nsigSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type M(MSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type asg(asgSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< double >::type SS(SSSEXP);
    Rcpp::traits::input_parameter< int >::type nclust(nclustSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sig(sigSEXP);
    Rcpp::traits::input_parameter< int >::type nsig(nsigSEXP);
    rcpp_result_gen = Rcpp::wrap(edfkmeans(X, M, asg, ns, SS, nclust, n, d, sig, nsig));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_edfkmeans_Pdist", (DL_FUNC) &_edfkmeans_Pdist, 2},
    {"_edfkmeans_edfkmeans", (DL_FUNC) &_edfkmeans_edfkmeans, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_edfkmeans(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
