# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Pdist <- function(A, B) {
    .Call(`_edfkmeans_Pdist`, A, B)
}

edfkmeans <- function(X, M, asg, ns, SS, nclust, n, d, sig, nsig) {
    .Call(`_edfkmeans_edfkmeans`, X, M, asg, ns, SS, nclust, n, d, sig, nsig)
}

