# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

edfkmeans <- function(X, M, MU, asg, ns, SS, nclust, n, d, sig, nsig) {
    .Call(`_edfkmeans_edfkmeans`, X, M, MU, asg, ns, SS, nclust, n, d, sig, nsig)
}

edfkmeans_all <- function(X, M, MU, asg, ns, SS, nclust, n, d, sig, nsig) {
    .Call(`_edfkmeans_edfkmeans_all`, X, M, MU, asg, ns, SS, nclust, n, d, sig, nsig)
}

k_reg <- function(x, y, h, n, ord) {
    .Call(`_edfkmeans_k_reg`, x, y, h, n, ord)
}

k_reg_loo <- function(x, y, h, n, ord) {
    .Call(`_edfkmeans_k_reg_loo`, x, y, h, n, ord)
}

